# Copyright (c) 2026, MariaDB plc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2.0,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
# the GNU General Public License, version 2.0, for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

"""Installing and removing the MySQL-to-MariaDB migration tooling.

The tooling is downloaded from GitHub and extracted into the user's data home,
one directory per release: ``~/.local/share/mariadb-migrator/<version>`` (see
:func:`mcp_plugin.lib.general.get_migrator_path`). It goes there rather than into
this plugin's data directory because it is a standalone program that outlives
any one plugin install, and the release is part of the path so that releases can
sit side by side. The release installed is pinned as
:data:`mcp_plugin.lib.general.MIGRATOR_VERSION`.

Downloading installs a ready-to-run copy: the archive is extracted
(:func:`download`), a virtual environment is built inside it with the
interpreter the MariaDB Shell bundles and the tooling's dependencies installed
into it (:func:`provision`), and a wrapper that runs that copy is put on the
user's PATH (:func:`install_wrapper`). No system Python is involved at any
point.

This is offered from :mod:`mcp_plugin.lib.setup`'s management menu only, never
from the first run - it is a download nothing else here depends on - and only on
the platforms the tooling runs on (see :func:`is_supported`).
"""

# cSpell:ignore mysqlsh MariaDB urllib

import os
import shlex
import shutil
import subprocess
import tempfile
import urllib.request
import venv
import zipfile

import mysqlsh

from mcp_plugin.lib import general, setup_prompts as prompts

# Where the migration tooling is fetched from: the source archive GitHub builds
# for a release tag, the tag being configured as
# :data:`mcp_plugin.lib.general.MIGRATOR_VERSION`. The archive contains a single
# top-level directory named after the project and the release, which is stripped
# on extraction, so the tooling's own layout (``mariadb-migrator``, ``scripts/``,
# ``sql/``, ...) ends up directly inside the target directory.
MIGRATOR_ARCHIVE_URL_TEMPLATE = (
    "https://github.com/mariadb-corporation/Mysql-to-MariaDB-Migration"
    "/archive/refs/tags/{version}.zip"
)

# How long (in seconds) to wait for the download before giving up. Generous
# enough for a slow link and short enough that an unreachable host does not look
# like a hung shell.
MIGRATOR_DOWNLOAD_TIMEOUT = 120

# Prefix for the working directories a download uses inside the tooling root -
# the staging copy, the copy being replaced, and the temp dir the archive is
# fetched into. Dot-prefixed so that :func:`installed_versions` can tell a
# release directory from a download in progress by name alone.
MIGRATOR_WORK_PREFIX = "."

# Name of the virtual environment the tooling's orchestrator runs in, created
# inside the install (see :func:`provision`). The tooling's own launcher sources
# ``.venv/bin/activate`` when it finds it, so this is the name it looks for -
# do not rename it.
MIGRATOR_VENV_DIR = ".venv"

# The tooling's dependency manifest, relative to its install directory.
MIGRATOR_REQUIREMENTS = os.path.join("orchestrator", "requirements.txt")

# How long (in seconds) to let the dependency install run before giving up.
MIGRATOR_PIP_TIMEOUT = 300

# First line of the generated wrapper, and how a wrapper of ours is told from
# an unrelated file that happens to have the same name. Anything without this
# marker is somebody else's and is never overwritten or deleted.
MIGRATOR_WRAPPER_MARKER = "# mariadb-migrator wrapper generated by mcp.setup"


def _venv_python(target_dir: str) -> str:
    """Returns the interpreter inside an install's virtual environment."""
    return os.path.join(target_dir, MIGRATOR_VENV_DIR, "bin", "python3")


def provision(target_dir: str) -> str:
    """Creates the tooling's virtual environment and installs its dependencies.

    The environment is built with the interpreter running this code - the one the
    MariaDB Shell bundles - so the tooling needs no system Python of its own. The
    result is an ordinary venv: its ``bin/python3`` is a real interpreter, and
    the tooling's launcher activates it exactly as it would one built by a system
    ``python3 -m venv``.

    Args:
        target_dir (str): The install to provision.

    Returns:
        The path of the virtual environment that was created.

    Raises:
        mysqlsh.Error: If the dependencies could not be installed.
    """
    venv_dir = os.path.join(target_dir, MIGRATOR_VENV_DIR)

    # symlinks=True is NOT optional, and is not EnvBuilder's default the way it
    # is `python -m venv`'s on POSIX. The shell's interpreter is built with
    # Py_ENABLE_SHARED and finds libpython through a loader path relative to
    # its own location, so a COPY of it inside the venv looks for that library
    # beside the copy and does not find it - the interpreter then dies before
    # it runs anything, with the loader's exit status 127. A symlink leaves the
    # resolved location, and therefore the library, where the interpreter
    # expects them.
    venv.EnvBuilder(with_pip=True, clear=True, symlinks=True).create(venv_dir)

    requirements = os.path.join(target_dir, MIGRATOR_REQUIREMENTS)
    if not os.path.isfile(requirements):
        # A release that ships no manifest is not an error: there is simply
        # nothing to install into the environment that was just created.
        return venv_dir

    result = subprocess.run(
        [
            _venv_python(target_dir),
            "-m", "pip", "install",
            "--quiet",
            "--disable-pip-version-check",
            "--require-virtualenv",
            "-r", requirements,
        ],
        cwd=target_dir,
        capture_output=True,
        text=True,
        timeout=MIGRATOR_PIP_TIMEOUT,
        check=False,
    )
    if result.returncode != 0:
        # pip's own diagnosis is far more useful than anything restated here.
        details = (result.stderr or result.stdout or "").strip()
        raise mysqlsh.Error(
            "Could not install the migration tooling's dependencies from "
            f"'{MIGRATOR_REQUIREMENTS}':\n{details}"
        )

    return venv_dir


def _wrapper_contents(target_dir: str) -> str:
    """Returns the wrapper script that runs one install of the tooling.

    The wrapper exists because the tooling has to be started from its own
    install directory - it resolves ``scripts/``, ``orchestrator/`` and
    ``config/`` relative to the working directory - and with its virtual
    environment active, since that is where its dependencies are and the
    launcher's own dependency check runs before it would activate anything
    itself.

    Args:
        target_dir (str): The install the wrapper is to run.

    Returns:
        The script's full text.
    """
    home = shlex.quote(target_dir)
    return f'''#!/bin/sh
{MIGRATOR_WRAPPER_MARKER} - DO NOT EDIT.
# Regenerated by every download and removed with the tooling. Points at:
#   {general.MIGRATOR_VERSION}
MIGRATOR_HOME={home}

if [ ! -x "$MIGRATOR_HOME/mariadb-migrator" ]; then
    echo "The migration tooling is not installed at '$MIGRATOR_HOME'." >&2
    echo "Run 'mariadb-shell -- mcp setup' to install it again." >&2
    exit 1
fi

# Run from the install directory: the tooling resolves its own scripts, its
# orchestrator package and the default config paths relative to the working
# directory, so relative arguments are relative to here too.
cd "$MIGRATOR_HOME" || exit 1

# Activate before handing over, so the launcher's dependency check - which runs
# before the launcher would source this itself - already sees the environment.
if [ -f "$MIGRATOR_HOME/{MIGRATOR_VENV_DIR}/bin/activate" ]; then
    . "$MIGRATOR_HOME/{MIGRATOR_VENV_DIR}/bin/activate"
fi

exec "$MIGRATOR_HOME/mariadb-migrator" "$@"
'''


def wrapper_path() -> str:
    """Returns where the wrapper that runs the tooling is installed."""
    return os.path.join(general.get_bin_home(), general.MIGRATOR_DIR_NAME)


def _wrapper_is_ours(path: str) -> bool:
    """Returns whether the file at the given path is a wrapper we generated.

    What is being guarded against is clobbering an unrelated program that
    happens to share the name - somebody's own ``mariadb-migrator`` on their
    PATH. A wrapper of ours carries :data:`MIGRATOR_WRAPPER_MARKER`; a symlink
    into the tooling root counts too, since that is the other shape an earlier
    install could plausibly have left.

    Args:
        path (str): The file to examine.

    Returns:
        True when the file is ours to replace or delete.
    """
    if os.path.islink(path):
        target = os.path.realpath(path)
        root = os.path.realpath(general.get_migrator_root())
        return target == root or target.startswith(root + os.sep)

    try:
        with open(path, "r", encoding="utf-8", errors="replace") as wrapper:
            # The marker is on the second line; reading a little is enough and
            # keeps a large unrelated binary from being slurped into memory.
            return MIGRATOR_WRAPPER_MARKER in wrapper.read(4096)
    except OSError:
        return False


def install_wrapper(target_dir: str) -> str:
    """Installs the wrapper that runs the given install, replacing an older one.

    Args:
        target_dir (str): The install the wrapper is to run.

    Returns:
        The path the wrapper was written to.

    Raises:
        mysqlsh.Error: If something that is not one of our wrappers is already
            installed under that name.
    """
    path = wrapper_path()
    if os.path.lexists(path) and not _wrapper_is_ours(path):
        raise mysqlsh.Error(
            f"'{path}' already exists and was not created by mcp.setup, so it "
            "was left alone. Move it aside and download the tooling again to "
            "have the wrapper installed there."
        )

    os.makedirs(os.path.dirname(path), exist_ok=True)

    # Written beside the target and moved into place, so that a wrapper on
    # somebody's PATH is never a half-written file.
    staging_path = path + ".new"
    with open(staging_path, "w", encoding="utf-8") as wrapper:
        wrapper.write(_wrapper_contents(target_dir))
    os.chmod(staging_path, 0o755)
    os.replace(staging_path, path)

    return path


def remove_wrapper() -> str:
    """Removes the wrapper, if the one installed is ours.

    Returns:
        The path that was removed, or an empty string when there was nothing of
        ours to remove.
    """
    path = wrapper_path()
    if not os.path.lexists(path) or not _wrapper_is_ours(path):
        return ""

    os.remove(path)

    return path


def is_supported() -> bool:
    """Returns whether the migration tooling runs on this platform.

    The tooling is a POSIX shell script entry point driving a directory of
    further shell scripts, so it runs on Linux and macOS but not on Windows,
    where there is no shell to run it with. Windows is therefore never offered
    the download: an install it cannot use would be a menu entry that only ever
    disappoints, and the plugin's own features do not depend on it.

    The test is for Windows rather than for Linux-or-macOS on purpose. What
    decides this is the POSIX shell, which every other platform this shell is
    built for has, so a new Unix should not have to be added here to get a
    feature that already works on it.

    Returns:
        True on every platform except Windows.
    """
    return os.name != "nt"


def archive_url() -> str:
    """Returns the URL the configured migration tooling release is fetched from.

    Returns:
        The download URL for :data:`mcp_plugin.lib.general.MIGRATOR_VERSION`.
    """
    return MIGRATOR_ARCHIVE_URL_TEMPLATE.format(version=general.MIGRATOR_VERSION)


def installed_versions() -> list:
    """Returns the releases of the migration tooling that are installed.

    Read off the directory names under :func:`general.get_migrator_root`, which
    is the only record of what a copy is - there is deliberately no version file
    inside an install to disagree with the path it sits at. Directories a
    download is working in are dot-prefixed (see :data:`MIGRATOR_WORK_PREFIX`)
    and are not releases.

    Returns:
        The installed releases, sorted; empty when none are.
    """
    try:
        entries = os.listdir(general.get_migrator_root())
    except OSError:
        # The root does not exist, so nothing is installed.
        return []

    return sorted(
        entry for entry in entries
        if not entry.startswith(MIGRATOR_WORK_PREFIX)
        and os.path.isdir(os.path.join(general.get_migrator_root(), entry))
    )


def _download_archive(url: str, archive_path: str) -> None:
    """Downloads the given URL to a local file.

    Args:
        url (str): The URL to download.
        archive_path (str): The file to write the response body to.

    Returns:
        None
    """
    with urllib.request.urlopen(url, timeout=MIGRATOR_DOWNLOAD_TIMEOUT) as response:
        with open(archive_path, "wb") as archive_file:
            shutil.copyfileobj(response, archive_file)


def _archive_prefix(members: list) -> str:
    """Returns the single top-level directory of an archive, if it has one.

    A source archive wraps everything in one directory named after the project
    and its branch, which is not part of the tooling's own layout and would
    otherwise have to be named by every caller. Stripping it is only safe when
    there really is just the one, so anything else yields no prefix.

    Args:
        members (list): The archive's :class:`zipfile.ZipInfo` entries.

    Returns:
        The prefix to strip, including its trailing slash, or an empty string.
    """
    top_level = {member.filename.split("/", 1)[0] for member in members if member.filename}
    nested = any("/" in member.filename.rstrip("/") for member in members)
    if len(top_level) == 1 and nested:
        return next(iter(top_level)) + "/"

    return ""


def _archive_destination(target_dir: str, relative_path: str) -> str:
    """Returns where an archive entry may be written, refusing to escape.

    An archive is remote input, and an entry naming ``../`` or an absolute path
    would have the extraction write outside the directory it was asked to fill.

    Args:
        target_dir (str): The directory being extracted into.
        relative_path (str): The entry's path within the archive.

    Returns:
        The absolute path to write the entry to.
    """
    base = os.path.abspath(target_dir)
    destination = os.path.abspath(os.path.join(base, relative_path))
    if destination != base and os.path.commonpath([base, destination]) != base:
        raise mysqlsh.Error(
            f"The downloaded archive contains an entry ('{relative_path}') that "
            "would be written outside the target directory. It was not extracted."
        )

    return destination


def _extract_archive(archive_path: str, target_dir: str) -> None:
    """Extracts a downloaded archive into the given directory.

    The archive's single top-level directory is stripped (see
    :func:`_archive_prefix`) and the recorded file modes are restored, which
    :meth:`zipfile.ZipFile.extractall` does not do - the migration tooling is a
    set of shell scripts plus the ``mariadb-migrator`` entry point, so without
    the executable bit nothing that was extracted can be run.

    Args:
        archive_path (str): The downloaded archive.
        target_dir (str): The directory to extract into; created if needed.

    Returns:
        None
    """
    with zipfile.ZipFile(archive_path) as archive:
        members = archive.infolist()
        prefix = _archive_prefix(members)

        os.makedirs(target_dir, exist_ok=True)
        for member in members:
            if not member.filename.startswith(prefix):
                continue

            relative_path = member.filename[len(prefix):]
            if not relative_path:
                continue

            destination = _archive_destination(target_dir, relative_path)
            if member.is_dir():
                os.makedirs(destination, exist_ok=True)
                continue

            os.makedirs(os.path.dirname(destination), exist_ok=True)
            with archive.open(member) as source:
                with open(destination, "wb") as extracted:
                    shutil.copyfileobj(source, extracted)

            mode = (member.external_attr >> 16) & 0o777
            if mode:
                os.chmod(destination, mode)


def download() -> str:
    """Downloads the MySQL-to-MariaDB migration tooling into the plugin data dir.

    The configured release (see :func:`archive_url`) is fetched and extracted
    into :func:`mcp_plugin.lib.general.get_migrator_path`, replacing whatever is
    installed there, and the release is recorded in the installed copy. The new
    copy is extracted next to the old one and only swapped in once it is
    complete, so a download that fails part-way through - or an archive that
    turns out to contain something it should not - leaves a previously installed
    copy exactly as it was.

    Returns:
        The directory the tooling was installed in.
    """
    root_dir = general.get_migrator_root()
    target_dir = general.get_migrator_path()
    work_name = MIGRATOR_WORK_PREFIX + general.MIGRATOR_VERSION
    staging_dir = os.path.join(root_dir, work_name + ".new")
    previous_dir = os.path.join(root_dir, work_name + ".old")

    # The root is this function's to create: nothing else has a reason to, and
    # its absence is what says no release is installed.
    os.makedirs(root_dir, exist_ok=True)

    # Anything left behind by an interrupted earlier run.
    shutil.rmtree(staging_dir, ignore_errors=True)
    shutil.rmtree(previous_dir, ignore_errors=True)

    # Downloaded inside the tooling root rather than into the system temp
    # directory: it is on the same filesystem as the target, so the finished
    # copy is moved into place rather than copied across devices.
    with tempfile.TemporaryDirectory(
        dir=root_dir, prefix=MIGRATOR_WORK_PREFIX + "download-"
    ) as download_dir:
        archive_path = os.path.join(download_dir, "migrator.zip")
        try:
            _download_archive(archive_url(), archive_path)
            _extract_archive(archive_path, staging_dir)
        except Exception:
            shutil.rmtree(staging_dir, ignore_errors=True)
            raise

    had_previous = os.path.isdir(target_dir)
    if had_previous:
        os.rename(target_dir, previous_dir)
    try:
        os.rename(staging_dir, target_dir)
    except OSError:
        # Put the copy that was working back before reporting the failure.
        if had_previous:
            os.rename(previous_dir, target_dir)
        shutil.rmtree(staging_dir, ignore_errors=True)
        raise

    shutil.rmtree(previous_dir, ignore_errors=True)

    return target_dir


def remove() -> str:
    """Removes every installed release of the MySQL-to-MariaDB migration tooling.

    The whole root goes, not just the configured release: releases accumulate
    there as the pin moves on, and a release the pin has moved past would
    otherwise have no way of ever being removed again short of deleting it by
    hand. Anything an interrupted download left behind goes with it, so that
    removing really does leave the data home as it was before the tooling was
    ever installed.

    Args:
        None

    Returns:
        The directory that was removed, whether or not it existed.
    """
    # The wrapper first: it is the thing on the user's PATH, and one pointing at
    # a tree that is no longer there is worse than none at all.
    remove_wrapper()

    root_dir = general.get_migrator_root()
    if os.path.isdir(root_dir):
        shutil.rmtree(root_dir)

    return root_dir


def is_installed() -> bool:
    """Returns whether the CONFIGURED release of the migration tooling is installed.

    This is the whole of what the setup offers to do with the tooling: install
    the configured release, or remove what is installed. There is deliberately no
    update step - bumping the pin and downloading installs the new release beside
    the old one, so an update is a download, and getting rid of the old copy is
    the remove step.

    Returns:
        True when the configured release is installed. Another release being
        installed does NOT make this true - see :func:`installed_versions`.
    """
    return os.path.isdir(general.get_migrator_path())


def menu_label() -> str:
    """Returns the menu entry for whatever the migration tooling now needs.

    Keyed on whether ANY release is installed rather than on the configured one,
    to stay consistent with what the entry then does: removal is all-or-nothing
    (see :func:`remove`), so with a release the pin has moved past still sitting
    there, the step on offer has to be removing it. Installing the configured
    release is then the download that follows - which is the same two-step flow
    that not having an update step always meant.
    """
    if installed_versions():
        return "Remove the MySQL-to-MariaDB migration tooling"

    return (
        "Download the MySQL-to-MariaDB migration tooling "
        f"({general.MIGRATOR_VERSION})"
    )


def _print_path_hint() -> None:
    """Says how to reach the wrapper when its directory is not on PATH."""
    bin_home = general.get_bin_home()
    path_entries = [
        os.path.abspath(entry)
        for entry in os.environ.get("PATH", "").split(os.pathsep)
        if entry
    ]
    if os.path.abspath(bin_home) in path_entries:
        print(f"Run it as '{general.MIGRATOR_DIR_NAME}'.")
        return

    # Worth saying outright: the wrapper is installed and executable but not
    # reachable by name, which looks like a failed install rather than a PATH
    # that has never included this directory.
    print(
        f"\nNOTE: '{bin_home}' is not on your PATH, so the wrapper cannot be "
        "run by name yet.\nAdd it, for example:\n"
    )
    print(f'  export PATH="{bin_home}:$PATH"')


def print_status() -> bool:
    """Prints which releases are installed and returns whether the configured one is."""
    installed = is_installed()
    others = [
        version for version in installed_versions()
        if version != general.MIGRATOR_VERSION
    ]

    if installed:
        print(
            f"\nMigration tooling ({general.MIGRATOR_VERSION}) installed in: "
            f"{general.get_migrator_path()}"
        )
    else:
        print(
            "\nMigration tooling not downloaded yet "
            f"(configured release: {general.MIGRATOR_VERSION})."
        )

    if others:
        # Releases the pin has moved past. Worth naming: they still take up
        # room, and removing is all-or-nothing, so they are what "remove" will
        # also take.
        print(f"  Other releases installed: {', '.join(others)}")

    return installed


def manage() -> None:
    """Downloads the migration tooling, or removes what is installed.

    Which of the two it is follows from what is installed: there is nothing to
    download while a copy is there, so what the setup offers then is removing
    it. Installing a different release means removing this one and downloading
    again.
    """
    print_status()

    if installed_versions():
        # Deleting is the one thing that cannot be undone by running the setup
        # again, so it is also the one question that does not suggest going ahead.
        installed = installed_versions()
        what = (
            f"all {len(installed)} installed releases"
            if len(installed) > 1 else "the migration tooling"
        )
        if not prompts.yes_no(
            f"Remove {what} from '{general.get_migrator_root()}'?",
            default=False,
        ):
            return

        try:
            removed_dir = remove()
        except OSError as error:
            print(f"Could not remove the migration tooling: {error}")
            return

        print(f"Migration tooling removed from '{removed_dir}'.")
        return

    if not prompts.yes_no(
        "Download the MySQL-to-MariaDB migration tooling "
        f"{general.MIGRATOR_VERSION}?",
        default=True,
    ):
        return

    print(f"Downloading {archive_url()} ...")
    try:
        target_dir = download()
    except Exception as error:  # noqa: BLE001 - surface any download failure
        print(f"Could not install the migration tooling: {error}")
        return

    print(f"Migration tooling {general.MIGRATOR_VERSION} installed in '{target_dir}'.")

    # Provisioning and the wrapper are reported separately from the download,
    # and a failure in either leaves the extracted copy in place: it is a
    # complete install of the tooling, just not yet a runnable one, and saying
    # which step failed is what tells the user that.
    print("Creating the virtual environment and installing dependencies ...")
    try:
        venv_dir = provision(target_dir)
    except Exception as error:  # noqa: BLE001 - surface any provisioning failure
        print(f"Could not prepare the virtual environment: {error}")
        print(f"The tooling itself is installed in '{target_dir}'.")
        return

    print(f"Virtual environment ready in '{venv_dir}'.")

    try:
        wrapper = install_wrapper(target_dir)
    except Exception as error:  # noqa: BLE001 - surface any wrapper failure
        print(f"Could not install the wrapper: {error}")
        print(
            "The tooling can still be run with "
            f"'cd {target_dir} && ./mariadb-migrator'."
        )
        return

    print(f"'{general.MIGRATOR_DIR_NAME}' wrapper installed as '{wrapper}'.")
    _print_path_hint()
