; Copyright (c) 2026, MariaDB plc and/or its affiliates.
[pytest]
junit_family = xunit1
addopts = --color=yes -ra --junitxml=plugin-tests.xml --cov-report term --cov-report xml:plugin-test-coverage.xml --cov-report html --cov-config=".coveragerc"
