/*
 * Copyright (c) 2026, MariaDB plc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License, version 2.0,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See
 * the GNU General Public License, version 2.0, for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
 */

import type { IColumnDetails } from "../mcp/types.js";
import type { IResultSet } from "../webview/protocol.js";
import { QueryBuilder } from "./queryBuilder.js";

/**
 * Builds the query builder for an editable result set.
 *
 * Both sides use this: the extension to run the changes, and the webview
 * to show the SQL they would run. Having one factory is what keeps the
 * preview honest - it is generated by the same code that will execute.
 *
 * @param resultSet The result set being edited.
 *
 * @returns The builder, or undefined when the result set is not bound to
 *          a table.
 */
export const createQueryBuilder = (
    resultSet: IResultSet,
): QueryBuilder | undefined => {
    if (!resultSet.target) {
        return undefined;
    }

    const columns = resultSet.columns.map((column): IColumnDetails => {
        return {
            name: column.name,
            datatype: column.datatype ?? "text",
            not_null: column.nullable === false ? 1 : 0,
            is_primary: column.isPrimary ? 1 : 0,
            is_unique: 0,
            is_generated: column.isGenerated ? 1 : 0,
            id_generation: column.isAutoIncrement ? "auto_inc" : null,
            comment: "",
            column_default: null,
        };
    });

    return new QueryBuilder(
        resultSet.target.schema,
        resultSet.target.table,
        columns,
    );
};
